apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
      queryTimeout: "60s"

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    user: default
    secureJsonData:
      password: ""
    jsonData:
      defaultDatabase: stone_mill
      protocol: http
      port: 8123
      server: clickhouse
